### ISSUE TITLE
`mitmproxy` fails to build, seems to be a dependency of home-manager..?

### ISSUE THREAD

**Issue by 06kellyjac** [rycee/home-manager#1412]
### Issue description

On a recent update of my system I had an issue trying to build `mitmproxy`

I ran this command `nix-store --query --referrers $(which mitmproxy)` to discover what depended on it and this is the output:

```log
/nix/store/60p10mrvkdxq403nn8jmqzfz75lps9gw-activation-script
/nix/store/9grnzljlgskfbs06639si9bc0krp8wg0-env-manifest.nix
/nix/store/854nk1kgkcbk2nicd11ki1x5bi59w5r8-user-environment
/nix/store/jpw3243251ckn8z642xdcl5rbsjjkmmd-home-manager-generation
```

I did a search for `mitmproxy` using GH's search but it didn't find anything.
Searching through my latest clone of `nixpkgs` master I haven't found any dependencies on `mitmproxy` either...

To get `mitmproxy` to successfully build for now I replaced it with a version that doesn't include any `checkInputs` or run `pytest` in the `checkPhase`

#### Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.53, NixOS, 20.09pre236091.28fce082c8c (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.7`
 - channels(root): `"home-manager, nixos-20.09pre236091.28fce082c8c, nixos-hardware"`
 - channels(user): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

`home-manager` channel: `home-manager https://github.com/rycee/home-manager/archive/master.tar.gz`

```nix
{ config, pkgs, ... }:

let
  hm = import <home-manager> {};
in {
  environment.systemPackages = with pkgs; [
    hm.home-manager
    # blah
  ];
  # blah
}
```

`home-manager switch` output:

```log
these derivations will be built:
  /nix/store/zbdwgjx7251z41l9nlpz32br2y7ichld-python3.7-asynctest-0.13.0.drv
  /nix/store/dnm57pw46d0q4s7jj928hgd7rs56fyvb-python3.7-mitmproxy-5.1.1.drv
  /nix/store/m1i4cz3xsfclhwdff9jbm70z6nf8f4hi-home-manager-path.drv
  /nix/store/nq8zlcs3n96lc3gii08q2x9fpa4rmn0r-activation-script.drv
  /nix/store/07iz957ylw1ybd4q589njxh5vp6cmkw1-home-manager-generation.drv
building '/nix/store/zbdwgjx7251z41l9nlpz32br2y7ichld-python3.7-asynctest-0.13.0.drv'...
Sourcing python-recompile-bytecode-hook.sh
Sourcing python-remove-tests-dir-hook
Sourcing python-catch-conflicts-hook.sh
Sourcing python-remove-bin-bytecode-hook.sh
Sourcing setuptools-build-hook
Using setuptoolsBuildPhase
Using setuptoolsShellHook
Sourcing pip-install-hook
Using pipInstallPhase
Sourcing python-imports-check-hook.sh
Using pythonImportsCheckPhase
Sourcing python-namespaces-hook
Sourcing setuptools-check-hook
unpacking sources
unpacking source archive /nix/store/d2arh6fd5iwng116a6faspxsjpfa1plh-asynctest-0.13.0.tar.gz
source root is asynctest-0.13.0
setting SOURCE_DATE_EPOCH to timestamp 1557852142 of file asynctest-0.13.0/setup.cfg
patching sources
configuring
no configure script, doing nothing
building
Executing setuptoolsBuildPhase
running bdist_wheel
running build
running build_py
creating build
creating build/lib
creating build/lib/asynctest
copying asynctest/selector.py -> build/lib/asynctest
copying asynctest/mock.py -> build/lib/asynctest
copying asynctest/helpers.py -> build/lib/asynctest
copying asynctest/case.py -> build/lib/asynctest
copying asynctest/_fail_on.py -> build/lib/asynctest
copying asynctest/__init__.py -> build/lib/asynctest
installing to build/bdist.linux-x86_64/wheel
running install
running install_lib
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/wheel
creating build/bdist.linux-x86_64/wheel/asynctest
copying build/lib/asynctest/__init__.py -> build/bdist.linux-x86_64/wheel/asynctest
copying build/lib/asynctest/_fail_on.py -> build/bdist.linux-x86_64/wheel/asynctest
copying build/lib/asynctest/case.py -> build/bdist.linux-x86_64/wheel/asynctest
copying build/lib/asynctest/helpers.py -> build/bdist.linux-x86_64/wheel/asynctest
copying build/lib/asynctest/mock.py -> build/bdist.linux-x86_64/wheel/asynctest
copying build/lib/asynctest/selector.py -> build/bdist.linux-x86_64/wheel/asynctest
running install_egg_info
running egg_info
writing asynctest.egg-info/PKG-INFO
writing dependency_links to asynctest.egg-info/dependency_links.txt
writing top-level names to asynctest.egg-info/top_level.txt
reading manifest file 'asynctest.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'asynctest.egg-info/SOURCES.txt'
Copying asynctest.egg-info to build/bdist.linux-x86_64/wheel/asynctest-0.13.0-py3.7.egg-info
running install_scripts
creating build/bdist.linux-x86_64/wheel/asynctest-0.13.0.dist-info/WHEEL
creating 'dist/asynctest-0.13.0-py3-none-any.whl' and adding 'build/bdist.linux-x86_64/wheel' to it
adding 'asynctest/__init__.py'
adding 'asynctest/_fail_on.py'
adding 'asynctest/case.py'
adding 'asynctest/helpers.py'
adding 'asynctest/mock.py'
adding 'asynctest/selector.py'
adding 'asynctest-0.13.0.dist-info/LICENSE.md'
adding 'asynctest-0.13.0.dist-info/METADATA'
adding 'asynctest-0.13.0.dist-info/WHEEL'
adding 'asynctest-0.13.0.dist-info/top_level.txt'
adding 'asynctest-0.13.0.dist-info/zip-safe'
adding 'asynctest-0.13.0.dist-info/RECORD'
removing build/bdist.linux-x86_64/wheel
Finished executing setuptoolsBuildPhase
installing
Executing pipInstallPhase
/build/asynctest-0.13.0/dist /build/asynctest-0.13.0
Processing ./asynctest-0.13.0-py3-none-any.whl
Installing collected packages: asynctest
Successfully installed asynctest-0.13.0
/build/asynctest-0.13.0
Finished executing pipInstallPhase
post-installation fixup
shrinking RPATHs of ELF executables and libraries in /nix/store/vwan19j2vans9ajz4bim1q0rvp9g1sf7-python3.7-asynctest-0.13.0
strip is /nix/store/k6rnzlmcvm37d0nw4fkz6ivmykmrdn39-binutils-2.31.1/bin/strip
stripping (with command strip and flags -S) in /nix/store/vwan19j2vans9ajz4bim1q0rvp9g1sf7-python3.7-asynctest-0.13.0/lib
patching script interpreter paths in /nix/store/vwan19j2vans9ajz4bim1q0rvp9g1sf7-python3.7-asynctest-0.13.0
checking for references to /build/ in /nix/store/vwan19j2vans9ajz4bim1q0rvp9g1sf7-python3.7-asynctest-0.13.0...
Executing pythonRemoveTestsDir
Finished executing pythonRemoveTestsDir
running install tests
......................................................................................................................................................................................E.../build/asynctest-0.13.0/asynctest/mock.py:950: RuntimeWarning: coroutine 'Test_patch_decorator_coroutine_or_generator_scope.test_patch_coroutine_with_multiple_scopes.<locals>.a_native_coroutine' was never awaited
  for patching in patchings:
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
.E/nix/store/wpw6qdjbrv7s72kk81n1lwf3vj6fldk2-python3-3.7.8/lib/python3.7/unittest/mock.py:1966: RuntimeWarning: coroutine 'Test_patch_decorator_coroutine_or_generator_scope_LIMITED.test_multiple_patches_on_coroutine.<locals>.a_native_coroutine' was never awaited
  self.name = name
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
/nix/store/wpw6qdjbrv7s72kk81n1lwf3vj6fldk2-python3-3.7.8/lib/python3.7/unittest/mock.py:1966: RuntimeWarning: coroutine 'Test_patch_decorator_coroutine_or_generator_scope_LIMITED.test_patch_coroutine_only_when_running.<locals>.a_native_coroutine' was never awaited
  self.name = name
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
EF...F................
======================================================================
ERROR: test_both_patch_and_patch_dict_with_scope_limited (test.test_mock.Test_patch_and_patch_dict_scope) [patch and patch.dict]
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/asynctest-0.13.0/test/test_mock.py", line 1603, in test_both_patch_and_patch_dict_with_scope_limited
    self.assertEqual((True, True), next(gen))
  File "/build/asynctest-0.13.0/asynctest/mock.py", line 995, in patched_generator
    return (yield from patched_factory(*args, **kwargs))
  File "/build/asynctest-0.13.0/asynctest/mock.py", line 985, in patched_factory
    patching.__exit__(*exc_info)
  File "/nix/store/wpw6qdjbrv7s72kk81n1lwf3vj6fldk2-python3-3.7.8/lib/python3.7/unittest/mock.py", line 1437, in __exit__
    return exit_stack.__exit__(*exc_info)
  File "/nix/store/wpw6qdjbrv7s72kk81n1lwf3vj6fldk2-python3-3.7.8/lib/python3.7/contextlib.py", line 482, in __exit__
    received_exc = exc_details[0] is not None
IndexError: tuple index out of range

< --           Removed 20 other error logs           -->
< -- See pastebin for full python test error logs:  -- >
< --         https://pastebin.com/vfArN5S3          -- >

======================================================================
FAIL: test_scope_limited (test.test_mock.Test_patch_dict_decorator_coroutine_or_generator_scope)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/asynctest-0.13.0/test/test_mock.py", line 1405, in test_scope_limited
    self.assertFalse(self.is_patched())
AssertionError: True is not false

----------------------------------------------------------------------
Ran 219 tests in 0.318s

FAILED (failures=6, errors=16)
builder for '/nix/store/zbdwgjx7251z41l9nlpz32br2y7ichld-python3.7-asynctest-0.13.0.drv' failed with exit code 1
cannot build derivation '/nix/store/dnm57pw46d0q4s7jj928hgd7rs56fyvb-python3.7-mitmproxy-5.1.1.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/m1i4cz3xsfclhwdff9jbm70z6nf8f4hi-home-manager-path.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/07iz957ylw1ybd4q589njxh5vp6cmkw1-home-manager-generation.drv': 1 dependencies couldn't be built
error: build of '/nix/store/07iz957ylw1ybd4q589njxh5vp6cmkw1-home-manager-generation.drv' failed
```

**Comment by rycee** [comment]
I imagine you have mitmproxy in `home.packages`, either directly or transitively and mitmproxy doesn't seem to build in Nixpkgs master [at the moment](https://hydra.nixos.org/build/124460433). It seems unlikely that Home Manager itself is causing this problem.

**Comment by 06kellyjac** [comment]
Right. I just don't know how to find out what is depending on it.

All `nix-store --query --referrers $(which mitmproxy)` gave me was generic home-manager stuff.
I'm not using it directly.
I had a search through `nixpkgs` for stuff that depends on it but i couldnt find anything.

How else can I find out what is requiring it?

**Comment by rycee** [comment]
You can try `nix why-depends` on the drv files or bisecting your configuration until it no longer depends on mitmproxy.

**Comment by 06kellyjac** [comment]
Ok I found it in one of my nix files :facepalm: 

Thanks :sweat_smile:
still loving home-manager
