### ISSUE TITLE
dropbox service doesn't start

### ISSUE THREAD

**Issue by bbigras** [rycee/home-manager#1419]
### Issue description

`services.dropbox` fails while running dropbox manually works.

I'm supposed to be on bb6eb9b13e3d40a22633fb80cbc75347af5bed3c

```
jui 30 15:48:40 desktop systemd[1757]: Starting dropbox...
jui 30 15:48:40 desktop b6yq15096azj3wyggqpvydrqibd2i332-dropbox-start[24368]: Traceback (most recent call last):
jui 30 15:48:40 desktop b6yq15096azj3wyggqpvydrqibd2i332-dropbox-start[24368]:   File "/nix/store/8hhwccs47i8ihv9i48vvlhsmfbcy9vb3-dropbox-cli-2020.03.04/bin/dropbox", line 1603, in <module>
jui 30 15:48:40 desktop b6yq15096azj3wyggqpvydrqibd2i332-dropbox-start[24368]:     ret = main(sys.argv)
jui 30 15:48:40 desktop b6yq15096azj3wyggqpvydrqibd2i332-dropbox-start[24368]:   File "/nix/store/8hhwccs47i8ihv9i48vvlhsmfbcy9vb3-dropbox-cli-2020.03.04/bin/dropbox", line 1592, in main
jui 30 15:48:40 desktop b6yq15096azj3wyggqpvydrqibd2i332-dropbox-start[24368]:     result = commands[argv[i]](argv[i+1:])
jui 30 15:48:40 desktop b6yq15096azj3wyggqpvydrqibd2i332-dropbox-start[24368]:   File "/nix/store/8hhwccs47i8ihv9i48vvlhsmfbcy9vb3-dropbox-cli-2020.03.04/bin/dropbox", line 862, in update
jui 30 15:48:40 desktop b6yq15096azj3wyggqpvydrqibd2i332-dropbox-start[24368]:     download()
jui 30 15:48:40 desktop b6yq15096azj3wyggqpvydrqibd2i332-dropbox-start[24368]:   File "/nix/store/8hhwccs47i8ihv9i48vvlhsmfbcy9vb3-dropbox-cli-2020.03.04/bin/dropbox", line 294, in download
jui 30 15:48:40 desktop b6yq15096azj3wyggqpvydrqibd2i332-dropbox-start[24368]:     import gi
jui 30 15:48:40 desktop b6yq15096azj3wyggqpvydrqibd2i332-dropbox-start[24368]: ModuleNotFoundError: No module named 'gi'
jui 30 15:48:40 desktop b6yq15096azj3wyggqpvydrqibd2i332-dropbox-start[24369]: Starting Dropbox...
jui 30 15:49:40 desktop b6yq15096azj3wyggqpvydrqibd2i332-dropbox-start[24369]: The Dropbox daemon is not installed!
jui 30 15:49:40 desktop b6yq15096azj3wyggqpvydrqibd2i332-dropbox-start[24369]: Run "dropbox start -i" to install the daemon
jui 30 15:49:40 desktop systemd[1757]: dropbox.service: Can't open PID file /home/bbigras/.dropbox-hm/.dropbox/dropbox.pid (yet?) after start: Operation not permitted
jui 30 15:49:40 desktop systemd[1757]: dropbox.service: Failed with result 'protocol'.
jui 30 15:49:40 desktop systemd[1757]: Failed to start dropbox.
```

#### Maintainer CC

@eyjhb

#### Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 5.7.11, NixOS, 20.09pre-git (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.7`
 - channels(bbigras): `"nixpkgs-20.09pre236138.970b2b853d4"`
 - channels(root): `""`
 - nixpkgs: `/home/bbigras/.nix-defexpr/channels/nixpkgs`

**Comment by rycee** [comment]
@bbigras Could you verify that `~/.config/systemd/user/dropbox.service` contains `DISPLAY=` inside the `Environment` field?

**Comment by bbigras** [comment]
Thanks for the reply. I'm not home right now, so I can't test on my desktop.

I can test on my laptop, which uses a lot of the same config files and I do have `DISPLAY=` and the service works.

So I'm suspecting my desktop wasn't properly updated or something like that.

**Comment by eyJhb** [comment]
In general I have had some issues with hm not updating the services after a rebuld, where I have to delete the files first before they get added again.

But I have no further evidence of that... :) Might as well be me! - But it does sound like it does not have DISPLAY unset :)

**Comment by rycee** [comment]
@eyJhb If you've been having problems with services restarting then I would suggest trying the sd-switch branch. It completely replaces the systemd service switchover code.

**Comment by tfmoraes** [comment]
@rycee Here it starts correctly, but the tray icon is not showing. Other problem is it set the Dropbox folder to ~/.dropbox-hm/Dropbox, not ~/Dropbox. I tried to set path to $HOME/Dropbox (and "${config.home.homeDirectory}/Dropbox";) but it didn't work.

**Comment by bbigras** [comment]
I'm back home.

I also have `DISPLAY=` on my desktop but the service fails.

I have:
```
[Install]
WantedBy=default.target

[Service]
Environment=HOME=/home/bbigras/.dropbox-hm DISPLAY=
ExecReload=/nix/store/vssdbs9s059qm5rqpw5q25z3c2d065f7-coreutils-8.31/bin/kill -HUP $MAINPID
ExecStart=/nix/store/b6yq15096azj3wyggqpvydrqibd2i332-dropbox-start
ExecStop=/nix/store/8hhwccs47i8ihv9i48vvlhsmfbcy9vb3-dropbox-cli-2020.03.04/bin/dropbox stop
Nice=10
PIDFile=/home/bbigras/.dropbox-hm/.dropbox/dropbox.pid
PrivateTmp=true
ProtectSystem=full
Restart=on-failure
Type=forking

[Unit]
Description=dropbox
```

```
-- Reboot --
jui 31 19:02:06 desktop systemd[1737]: Starting dropbox...
jui 31 19:02:06 desktop b6yq15096azj3wyggqpvydrqibd2i332-dropbox-start[1753]: Traceback (most recent call last):
jui 31 19:02:06 desktop b6yq15096azj3wyggqpvydrqibd2i332-dropbox-start[1753]:   File "/nix/store/8hhwccs47i8ihv9i48vvlhsmfbcy9vb3-dropbox-cli-2020.03.04/bin/dropbox", line 1603, in <module>
jui 31 19:02:06 desktop b6yq15096azj3wyggqpvydrqibd2i332-dropbox-start[1753]:     ret = main(sys.argv)
jui 31 19:02:06 desktop b6yq15096azj3wyggqpvydrqibd2i332-dropbox-start[1753]:   File "/nix/store/8hhwccs47i8ihv9i48vvlhsmfbcy9vb3-dropbox-cli-2020.03.04/bin/dropbox", line 1592, in main
jui 31 19:02:06 desktop b6yq15096azj3wyggqpvydrqibd2i332-dropbox-start[1753]:     result = commands[argv[i]](argv[i+1:])
jui 31 19:02:06 desktop b6yq15096azj3wyggqpvydrqibd2i332-dropbox-start[1753]:   File "/nix/store/8hhwccs47i8ihv9i48vvlhsmfbcy9vb3-dropbox-cli-2020.03.04/bin/dropbox", line 862, in update
jui 31 19:02:06 desktop b6yq15096azj3wyggqpvydrqibd2i332-dropbox-start[1753]:     download()
jui 31 19:02:06 desktop b6yq15096azj3wyggqpvydrqibd2i332-dropbox-start[1753]:   File "/nix/store/8hhwccs47i8ihv9i48vvlhsmfbcy9vb3-dropbox-cli-2020.03.04/bin/dropbox", line 294, in download
jui 31 19:02:06 desktop b6yq15096azj3wyggqpvydrqibd2i332-dropbox-start[1753]:     import gi
jui 31 19:02:06 desktop b6yq15096azj3wyggqpvydrqibd2i332-dropbox-start[1753]: ModuleNotFoundError: No module named 'gi'
jui 31 19:02:06 desktop b6yq15096azj3wyggqpvydrqibd2i332-dropbox-start[1770]: Starting Dropbox...
jui 31 19:02:06 desktop b6yq15096azj3wyggqpvydrqibd2i332-dropbox-start[1783]: Starting Dropbox...
jui 31 19:02:06 desktop b6yq15096azj3wyggqpvydrqibd2i332-dropbox-start[1783]: at: /home/bbigras/.dropbox-hm/.d: No such file or directory
jui 31 19:03:07 desktop b6yq15096azj3wyggqpvydrqibd2i332-dropbox-start[1770]: The Dropbox daemon is not installed!
jui 31 19:03:07 desktop b6yq15096azj3wyggqpvydrqibd2i332-dropbox-start[1770]: Run "dropbox start -i" to install the daemon
jui 31 19:03:07 desktop systemd[1737]: dropbox.service: Can't open PID file /home/bbigras/.dropbox-hm/.dropbox/dropbox.pid (yet?) after start: Operation not permitted
jui 31 19:03:07 desktop systemd[1737]: dropbox.service: Failed with result 'protocol'.
jui 31 19:03:07 desktop systemd[1737]: Failed to start dropbox.
jui 31 19:03:07 desktop systemd[1737]: dropbox.service: Scheduled restart job, restart counter is at 1.
jui 31 19:03:07 desktop systemd[1737]: Stopped dropbox.
jui 31 19:03:07 desktop systemd[1737]: Starting dropbox...
jui 31 19:03:07 desktop b6yq15096azj3wyggqpvydrqibd2i332-dropbox-start[2967]: Traceback (most recent call last):
jui 31 19:03:07 desktop b6yq15096azj3wyggqpvydrqibd2i332-dropbox-start[2967]:   File "/nix/store/8hhwccs47i8ihv9i48vvlhsmfbcy9vb3-dropbox-cli-2020.03.04/bin/dropbox", line 1603, in <module>
jui 31 19:03:07 desktop b6yq15096azj3wyggqpvydrqibd2i332-dropbox-start[2967]:     ret = main(sys.argv)
jui 31 19:03:07 desktop b6yq15096azj3wyggqpvydrqibd2i332-dropbox-start[2967]:   File "/nix/store/8hhwccs47i8ihv9i48vvlhsmfbcy9vb3-dropbox-cli-2020.03.04/bin/dropbox", line 1592, in main
jui 31 19:03:07 desktop b6yq15096azj3wyggqpvydrqibd2i332-dropbox-start[2967]:     result = commands[argv[i]](argv[i+1:])
jui 31 19:03:07 desktop b6yq15096azj3wyggqpvydrqibd2i332-dropbox-start[2967]:   File "/nix/store/8hhwccs47i8ihv9i48vvlhsmfbcy9vb3-dropbox-cli-2020.03.04/bin/dropbox", line 862, in update
jui 31 19:03:07 desktop b6yq15096azj3wyggqpvydrqibd2i332-dropbox-start[2967]:     download()
jui 31 19:03:07 desktop b6yq15096azj3wyggqpvydrqibd2i332-dropbox-start[2967]:   File "/nix/store/8hhwccs47i8ihv9i48vvlhsmfbcy9vb3-dropbox-cli-2020.03.04/bin/dropbox", line 294, in download
jui 31 19:03:07 desktop b6yq15096azj3wyggqpvydrqibd2i332-dropbox-start[2967]:     import gi
jui 31 19:03:07 desktop b6yq15096azj3wyggqpvydrqibd2i332-dropbox-start[2967]: ModuleNotFoundError: No module named 'gi'
jui 31 19:03:07 desktop b6yq15096azj3wyggqpvydrqibd2i332-dropbox-start[2970]: Starting Dropbox...
jui 31 19:03:07 desktop b6yq15096azj3wyggqpvydrqibd2i332-dropbox-start[2984]: Start/home/bbigras/.dropbox-hm/.dropbox-dist/VERSION: No such file or directory
jui 31 19:04:07 desktop b6yq15096azj3wyggqpvydrqibd2i332-dropbox-start[2970]: The Dropbox daemon is not installed!
jui 31 19:04:07 desktop b6yq15096azj3wyggqpvydrqibd2i332-dropbox-start[2970]: Run "dropbox start -i" to install the daemon
jui 31 19:04:07 desktop systemd[1737]: dropbox.service: Can't open PID file /home/bbigras/.dropbox-hm/.dropbox/dropbox.pid (yet?) after start: Operation not permitted
jui 31 19:04:07 desktop systemd[1737]: dropbox.service: Failed with result 'protocol'.
jui 31 19:04:07 desktop systemd[1737]: Failed to start dropbox.
jui 31 19:04:08 desktop systemd[1737]: dropbox.service: Scheduled restart job, restart counter is at 2.
jui 31 19:04:08 desktop systemd[1737]: Stopped dropbox.
jui 31 19:04:08 desktop systemd[1737]: Starting dropbox...
jui 31 19:04:08 desktop b6yq15096azj3wyggqpvydrqibd2i332-dropbox-start[3451]: Traceback (most recent call last):
jui 31 19:04:08 desktop b6yq15096azj3wyggqpvydrqibd2i332-dropbox-start[3451]:   File "/nix/store/8hhwccs47i8ihv9i48vvlhsmfbcy9vb3-dropbox-cli-2020.03.04/bin/dropbox", line 1603, in <module>
jui 31 19:04:08 desktop b6yq15096azj3wyggqpvydrqibd2i332-dropbox-start[3451]:     ret = main(sys.argv)
jui 31 19:04:08 desktop b6yq15096azj3wyggqpvydrqibd2i332-dropbox-start[3451]:   File "/nix/store/8hhwccs47i8ihv9i48vvlhsmfbcy9vb3-dropbox-cli-2020.03.04/bin/dropbox", line 1592, in main
jui 31 19:04:08 desktop b6yq15096azj3wyggqpvydrqibd2i332-dropbox-start[3451]:     result = commands[argv[i]](argv[i+1:])
jui 31 19:04:08 desktop b6yq15096azj3wyggqpvydrqibd2i332-dropbox-start[3451]:   File "/nix/store/8hhwccs47i8ihv9i48vvlhsmfbcy9vb3-dropbox-cli-2020.03.04/bin/dropbox", line 862, in update
jui 31 19:04:08 desktop b6yq15096azj3wyggqpvydrqibd2i332-dropbox-start[3451]:     download()
jui 31 19:04:08 desktop b6yq15096azj3wyggqpvydrqibd2i332-dropbox-start[3451]:   File "/nix/store/8hhwccs47i8ihv9i48vvlhsmfbcy9vb3-dropbox-cli-2020.03.04/bin/dropbox", line 294, in download
jui 31 19:04:08 desktop b6yq15096azj3wyggqpvydrqibd2i332-dropbox-start[3451]:     import gi
jui 31 19:04:08 desktop b6yq15096azj3wyggqpvydrqibd2i332-dropbox-start[3451]: ModuleNotFoundError: No module named 'gi'
jui 31 19:04:08 desktop b6yq15096azj3wyggqpvydrqibd2i332-dropbox-start[3452]: Starting Dropbox...
```

**Comment by bbigras** [comment]
I wonder if it's normal that I have:

/home/bbigras/.config/systemd/user/dropbox.service.d/override.conf
```
[Service]
Environment=DISPLAY=:1
```

**Comment by eyJhb** [comment]
> @rycee Here it starts correctly, but the tray icon is not showing. Other problem is it set the Dropbox folder to ~/.dropbox-hm/Dropbox, not ~/Dropbox. I tried to set path to $HOME/Dropbox (and "${config.home.homeDirectory}/Dropbox";) but it didn't work.

That is by design, and should affect nothing as it will symlink the important files (.dropbox, .dropbox-dist) to your ~. This is to give the ability, to place the Dropbox folder where you want.
The icon wil not be showing, because `DISPLAY` is unset I would assume.

**Comment by eyJhb** [comment]
@bbigras  I guess the tray icon will not be showing, as the comment I left above. Would be weird for Dropbox to show the tray icon, when DISPLAY is unset (assumed).

**Comment by bbigras** [comment]
Thanks. I don't get it why my override.conf file would prevent the service from starting. Unless the problem was fixed by running `systemctl --user daemon-reload`. Which was required after removing the override file.

**Comment by eyJhb** [comment]
> Thanks. I don't get it why my override.conf file would prevent the service from starting. Unless the problem was fixed by running `systemctl --user daemon-reload`. Which was required after removing the override file.

The service cannot start with DISPLAY set, as it will try to import a depency that it does not have. So the override would have done so thay it couldn't start. 

Not optimal, but a lot better than not working :) Dropbox-cli needs to be fixed upstream

**Comment by bbigras** [comment]
One weird thing is that it is working now with my override file, I see the icon and it seems to be syncing.

But for some reason I had to log back in at some point and it seems to be redownloading everything that I already had. Maybe there was some problem with my computer running out of space earlier.

**Comment by eyJhb** [comment]
@bbigras  is it working well enough to close this? Could open a new/reopen if any more issues come up :)

**Comment by bbigras** [comment]
I guess. I'm not 100% sure but I think it can cause a problem in the current state for "not yet authenticated" users since their browser won't open up automatically.

Did someone else beside me test it? I think I had to run dropbox manually but the same way to prevent it from using ~/Dropbox without the symlink.

**Comment by eyJhb** [comment]
Once you write `dropbox status` you get a link for activating Dropbox/linking it :)

**Comment by bbigras** [comment]
Gotcha. Thanks.

I'll open another issue about maybe adding DISPLAY conditionally.

**Comment by eyJhb** [comment]
We need to fix the upstream issue then I would assume :/ But yeah! :)
